[package]
name = "sp-blockchain"
version = "17.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate blockchain traits and primitives."
documentation = "https://docs.rs/sp-blockchain"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = ["derive"] }
futures = "0.3.21"
log = "0.4.17"
lru = "0.8.1"
parking_lot = "0.12.1"
thiserror = "1.0.30"
sp-api = { version = "15.0.0", path = "../api" }
sp-consensus = { version = "0.21.0", path = "../consensus/common" }
sp-database = { version = "4.0.0", path = "../database" }
sp-runtime = { version = "19.0.0", path = "../runtime" }
sp-state-machine = { version = "0.23.0", path = "../state-machine" }
